name: CI

on:
  pull_request:
    branches:
      - main


jobs: 
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      CFLAGS: '-arch x86_64 -arch arm64'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install docker compose
        run: |
          echo $CFLAGS
          echo "helo world"
          echo "helo world"